# Generated by Django 4.2.3 on 2024-04-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmClnt', models.CharField(max_length=255)),
                ('endrNtrg', models.TextField()),
                ('dtEntrega', models.DateTimeField()),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='pagamento.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmItm', models.CharField(max_length=100)),
                ('qntdd', models.IntegerField()),
                ('prcUnit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='delivery.entrega')),
            ],
        ),
    ]
